//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elite_Hockey_Manager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elite_Hockey_Manager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checkmark {
            get {
                object obj = ResourceManager.GetObject("checkmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pittsburgh
        ///Chicago
        ///New York
        ///Buffalo
        ///Erie
        ///Seattle
        ///San Francisco
        ///Los Angeles
        ///Dallas
        ///Tampa Bay
        ///Miami
        ///Detroit
        ///Toronto
        ///Montreal
        ///Philadelphia
        ///Moscow
        ///London
        ///Boston
        ///Nashville
        ///Cleveland
        ///Denver
        ///Columbus
        ///San Jose
        ///Las Vegas
        ///D.C
        ///Houston
        ///Pheonix
        ///San Antonio
        ///San Diego
        ///Jacksonville
        ///Indianapolis
        ///Portland
        ///Baltimore
        ///Louisville
        ///Mexico City
        ///Oklahoma City
        ///Atlanta
        ///Oshawa
        ///St. Louis
        ///New Jersey
        ///Falls Perk.
        /// </summary>
        internal static string cityNames {
            get {
                return ResourceManager.GetString("cityNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaron
        ///Abdul
        ///Abe
        ///Abel
        ///Abraham
        ///Abram
        ///Adalberto
        ///Adam
        ///Adan
        ///Adolfo
        ///Adolph
        ///Adrian
        ///Agustin
        ///Ahmad
        ///Ahmed
        ///Al
        ///Alan
        ///Albert
        ///Alberto
        ///Alden
        ///Aldo
        ///Alec
        ///Alejandro
        ///Alex
        ///Alexander
        ///Alexis
        ///Alfonso
        ///Alfonzo
        ///Alfred
        ///Alfredo
        ///Ali
        ///Allan
        ///Allen
        ///Alonso
        ///Alonzo
        ///Alphonse
        ///Alphonso
        ///Alton
        ///Alva
        ///Alvaro
        ///Alvin
        ///Amado
        ///Ambrose
        ///Amos
        ///Anderson
        ///Andre
        ///Andrea
        ///Andreas
        ///Andres
        ///Andrew
        ///Andy
        ///Angel
        ///Angelo
        ///Anibal
        ///Anthony
        ///Antione
        ///Antoine
        ///Anton
        ///Antone
        ///Antonia
        ///Antonio
        ///Antony
        ///Antwan
        ///Archie
        ///Arden
        ///Ariel
        ///Ar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string firstNames {
            get {
                return ResourceManager.GetString("firstNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Images {
            get {
                object obj = ResourceManager.GetObject("Images", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaberg
        ///Aaby
        ///Aadland
        ///Aagaard
        ///Aakre
        ///Aaland
        ///Aalbers
        ///Aalderink
        ///Aalund
        ///Aamodt
        ///Aamot
        ///Aanderud
        ///Aanenson
        ///Aanerud
        ///Aarant
        ///Aardema
        ///Aarestad
        ///Aarhus
        ///Aaron
        ///Aarons
        ///Aaronson
        ///Aarsvold
        ///Aas
        ///Aasby
        ///Aase
        ///Aasen
        ///Aavang
        ///Abad
        ///Abadi
        ///Abadie
        ///Abair
        ///Abaja
        ///Abajian
        ///Abalos
        ///Abaloz
        ///Abar
        ///Abarca
        ///Abare
        ///Abascal
        ///Abasta
        ///Abate
        ///Abati
        ///Abatiell
        ///Abato
        ///Abatti
        ///Abaunza
        ///Abaya
        ///Abbadessa
        ///Abbamonte
        ///Abbas
        ///Abbasi
        ///Abbassi
        ///Abbate
        ///Abbatiello
        ///Abbay
        ///Abbe
        ///Abbed
        ///Abbenante
        ///Abbey
        ///Abbinanti
        ///Abbington
        ///Abbitt
        ///Abb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lastNames {
            get {
                return ResourceManager.GetString("lastNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pirates
        ///Red Sox
        ///Chumbawambas
        ///Big Foots
        ///Tiny Foots
        ///Red Bulls
        ///Redskins
        ///Nationals
        ///Woodpeckers
        ///Bears
        ///Bunnies
        ///Slowies
        ///Cupcakes
        ///Glue Eaters
        ///Anteaters
        ///Losers
        ///Winners
        ///Benkies
        ///Clouds
        ///Hippies
        ///Hilltops
        ///Grooves
        ///Groovies
        ///Canibals
        ///Bowling Balls
        ///Pop Tarts
        ///Sparkles
        ///Fairies
        ///Alligators
        ///Aliens
        ///Barnies
        ///Goonies
        ///Purple People Eaters
        ///Trademarks
        ///Oompa-Loompas
        ///Shorties
        ///Timmies
        ///Hillbillies
        ///Treehuggers
        ///Sneks.
        /// </summary>
        internal static string teamNames {
            get {
                return ResourceManager.GetString("teamNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xmark {
            get {
                object obj = ResourceManager.GetObject("xmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
